In [3]:
import numpy 

In [4]:
type(numpy)

module

In [5]:
dir(numpy)

['ALLOW_THREADS',
 'AxisError',
 'BUFSIZE',
 'CLIP',
 'ComplexWarning',
 'DataSource',
 'ERR_CALL',
 'ERR_DEFAULT',
 'ERR_IGNORE',
 'ERR_LOG',
 'ERR_PRINT',
 'ERR_RAISE',
 'ERR_WARN',
 'FLOATING_POINT_SUPPORT',
 'FPE_DIVIDEBYZERO',
 'FPE_INVALID',
 'FPE_OVERFLOW',
 'FPE_UNDERFLOW',
 'False_',
 'Inf',
 'Infinity',
 'MAXDIMS',
 'MAY_SHARE_BOUNDS',
 'MAY_SHARE_EXACT',
 'ModuleDeprecationWarning',
 'NAN',
 'NINF',
 'NZERO',
 'NaN',
 'PINF',
 'PZERO',
 'RAISE',
 'RankWarning',
 'SHIFT_DIVIDEBYZERO',
 'SHIFT_INVALID',
 'SHIFT_OVERFLOW',
 'SHIFT_UNDERFLOW',
 'ScalarType',
 'Tester',
 'TooHardError',
 'True_',
 'UFUNC_BUFSIZE_DEFAULT',
 'UFUNC_PYVALS_NAME',
 'VisibleDeprecationWarning',
 'WRAP',
 '_CopyMode',
 '_NoValue',
 '_UFUNC_API',
 '__NUMPY_SETUP__',
 '__all__',
 '__builtins__',
 '__cached__',
 '__config__',
 '__deprecated_attrs__',
 '__dir__',
 '__doc__',
 '__expired_functions__',
 '__file__',
 '__getattr__',
 '__git_version__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 

In [6]:
marks=[20,33,54,44]

In [7]:
type(marks)

list

In [8]:
import numpy as np

In [9]:
data1=np.array(marks)

In [10]:
print(data1)

[20 33 54 44]


In [11]:
type(data1)

numpy.ndarray

In [12]:
dir(data1)

['T',
 '__abs__',
 '__add__',
 '__and__',
 '__array__',
 '__array_finalize__',
 '__array_function__',
 '__array_interface__',
 '__array_prepare__',
 '__array_priority__',
 '__array_struct__',
 '__array_ufunc__',
 '__array_wrap__',
 '__bool__',
 '__class__',
 '__class_getitem__',
 '__complex__',
 '__contains__',
 '__copy__',
 '__deepcopy__',
 '__delattr__',
 '__delitem__',
 '__dir__',
 '__divmod__',
 '__dlpack__',
 '__dlpack_device__',
 '__doc__',
 '__eq__',
 '__float__',
 '__floordiv__',
 '__format__',
 '__ge__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__iand__',
 '__ifloordiv__',
 '__ilshift__',
 '__imatmul__',
 '__imod__',
 '__imul__',
 '__index__',
 '__init__',
 '__init_subclass__',
 '__int__',
 '__invert__',
 '__ior__',
 '__ipow__',
 '__irshift__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__ixor__',
 '__le__',
 '__len__',
 '__lshift__',
 '__lt__',
 '__matmul__',
 '__mod__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__or__',
 '__pos__',

In [13]:
data1[0]

20

In [14]:
for v in data1:
    print(v)

20
33
54
44


In [15]:
data1[1:3]

array([33, 54])

In [16]:
data1[3:1]

array([], dtype=int32)

In [17]:
data1[-1:-2]

array([], dtype=int32)

In [18]:
data1[-2:-1]

array([54])

In [19]:
data1.max()

54

In [20]:
data1.min()

20

In [21]:
data1.copy()

array([20, 33, 54, 44])

In [22]:
student_marks=[[22,33,54,44],[33,44,22,35],[33,33,55,33]]

In [23]:
data2=np.array(student_marks)

In [24]:
data2

array([[22, 33, 54, 44],
       [33, 44, 22, 35],
       [33, 33, 55, 33]])

In [25]:
data2[1][1]

44

In [26]:
data2[1:,2:]

array([[22, 35],
       [55, 33]])

In [27]:
data2[:,:2]

array([[22, 33],
       [33, 44],
       [33, 33]])

In [28]:
data3=np.array([[1,0,5,5],[20,0,0,0],[5,5,5,5]])

In [29]:
data3

array([[ 1,  0,  5,  5],
       [20,  0,  0,  0],
       [ 5,  5,  5,  5]])

In [30]:
from scipy import sparse

In [31]:
data4=sparse.csr_matrix(data3)

In [32]:
print(data4)

  (0, 0)	1
  (0, 2)	5
  (0, 3)	5
  (1, 0)	20
  (2, 0)	5
  (2, 1)	5
  (2, 2)	5
  (2, 3)	5


In [33]:
dir(data4)

['__abs__',
 '__add__',
 '__array_priority__',
 '__bool__',
 '__class__',
 '__delattr__',
 '__dict__',
 '__dir__',
 '__div__',
 '__doc__',
 '__eq__',
 '__format__',
 '__ge__',
 '__getattr__',
 '__getattribute__',
 '__getitem__',
 '__gt__',
 '__hash__',
 '__iadd__',
 '__idiv__',
 '__imul__',
 '__init__',
 '__init_subclass__',
 '__isub__',
 '__iter__',
 '__itruediv__',
 '__le__',
 '__len__',
 '__lt__',
 '__matmul__',
 '__module__',
 '__mul__',
 '__ne__',
 '__neg__',
 '__new__',
 '__nonzero__',
 '__pow__',
 '__radd__',
 '__rdiv__',
 '__reduce__',
 '__reduce_ex__',
 '__repr__',
 '__rmatmul__',
 '__rmul__',
 '__round__',
 '__rsub__',
 '__rtruediv__',
 '__setattr__',
 '__setitem__',
 '__sizeof__',
 '__str__',
 '__sub__',
 '__subclasshook__',
 '__truediv__',
 '__weakref__',
 '_add_dense',
 '_add_sparse',
 '_arg_min_or_max',
 '_arg_min_or_max_axis',
 '_ascontainer',
 '_asindices',
 '_binopt',
 '_bsr_container',
 '_container',
 '_coo_container',
 '_cs_matrix__get_has_canonical_format',
 '_cs_ma

In [34]:
dir(sparse)

['SparseEfficiencyWarning',
 'SparseWarning',
 '__all__',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__path__',
 '__spec__',
 '_arrays',
 '_base',
 '_bsr',
 '_compressed',
 '_construct',
 '_coo',
 '_csc',
 '_csparsetools',
 '_csr',
 '_data',
 '_dia',
 '_dok',
 '_extract',
 '_index',
 '_lil',
 '_matrix_io',
 '_sparsetools',
 '_sputils',
 '_warnings',
 'base',
 'block_diag',
 'bmat',
 'bsr',
 'bsr_array',
 'bsr_matrix',
 'compressed',
 'construct',
 'coo',
 'coo_array',
 'coo_matrix',
 'csc',
 'csc_array',
 'csc_matrix',
 'csgraph',
 'csr',
 'csr_array',
 'csr_matrix',
 'data',
 'dia',
 'dia_array',
 'dia_matrix',
 'diags',
 'dok',
 'dok_array',
 'dok_matrix',
 'extract',
 'eye',
 'find',
 'hstack',
 'identity',
 'issparse',
 'isspmatrix',
 'isspmatrix_bsr',
 'isspmatrix_coo',
 'isspmatrix_csc',
 'isspmatrix_csr',
 'isspmatrix_dia',
 'isspmatrix_dok',
 'isspmatrix_lil',
 'kron',
 'kronsum',
 'lil',
 'lil_array',
 'lil_matrix',
 

In [35]:
data3

array([[ 1,  0,  5,  5],
       [20,  0,  0,  0],
       [ 5,  5,  5,  5]])

In [36]:
data3.shape

(3, 4)

In [37]:
data3.size

12

In [38]:
data3.ndim

2

In [39]:
data6=np.array([[1,2,3],[4,5,6],[7,8,9]])

In [40]:
data6

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [41]:
data6+10

array([[11, 12, 13],
       [14, 15, 16],
       [17, 18, 19]])

In [42]:
np.max(data6)

9

In [43]:
np.min(data6)

1

In [44]:
data7=np.array([[1,2,3],[4,5,6]])

In [45]:
data7

array([[1, 2, 3],
       [4, 5, 6]])

In [46]:
data7.reshape(3,2)

array([[1, 2],
       [3, 4],
       [5, 6]])

In [47]:
data7.reshape(1,6)

array([[1, 2, 3, 4, 5, 6]])

In [48]:
data7.reshape(6,1)

array([[1],
       [2],
       [3],
       [4],
       [5],
       [6]])

In [49]:
data8=np.array([[1,2,3],[4,5,6]])

In [51]:
data8

array([[1, 2, 3],
       [4, 5, 6]])

In [52]:
data8.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [53]:
data9=np.array([[1,2,3],[4,5,6]])

In [54]:
data9

array([[1, 2, 3],
       [4, 5, 6]])

In [55]:
data9.flatten()

array([1, 2, 3, 4, 5, 6])

In [58]:
data10=np.array([[1,2],[3,4]])

In [59]:
data10

array([[1, 2],
       [3, 4]])

In [60]:
data10.diagonal()

array([1, 4])

In [61]:
data10.trace()

5

In [62]:
data11=np.array([[1,2],[3,4]])

In [63]:
data12=np.array([[5,6],[7,8]])

In [64]:
data11+data12

array([[ 6,  8],
       [10, 12]])

In [65]:
data11-data12

array([[-4, -4],
       [-4, -4]])

In [66]:
np.dot(data11,data12)

array([[19, 22],
       [43, 50]])

In [67]:
data11*data12

array([[ 5, 12],
       [21, 32]])